---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: lightgbm
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  runPolicy: Serial
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: jupyter-datascience-notebook:2023.2
  source:
    git:
      uri: https://github.com/redhat-na-ssa/rhods-custom-notebook-example.git
      ref: odh
    contextDir: demo/custom-notebook-image
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: jupyter-datascience-notebook:2023.2
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: lightgbm:3.3.5
