FROM quay.io/opendatahub/workbench-images:jupyter-datascience-ubi9-python-3.9-2023b-20231027-cf1b63e

COPY Pipfile.lock /opt/app-root/bin/

RUN cd /opt/app-root/bin \
    && micropipenv install \
    && rm -f Pipfile.lock \
    && chmod -R g+w /opt/app-root/lib/python3.9/site-packages \
    && fix-permissions /opt/app-root -P
