apiVersion: image.openshift.io/v1
kind: ImageStreamTag
metadata:
  name: lightgbm:3.3.5
  annotations:
    opendatahub.io/notebook-python-dependencies: >-
      [{"name":"Boto3","version":"1.28"},{"name":"Kafka-Python","version":"2.0"},{"name":"Kfp-tekton","version":"1.5"},{"name":"Matplotlib","version":"3.6"},{"name":"Numpy","version":"1.24"},{"name":"Pandas","version":"1.5"},{"name":"Scikit-learn","version":"1.3"},{"name":"Scipy","version":"1.11"},{"name":"Elyra","version":"3.15"},{"name":"PyMongo","version":"4.5"},{"name":"Pyodbc","version":"4.0"},
      {"name":"Codeflare-SDK","version":"0.8"},
      {"name":"Sklearn-onnx","version":"1.15"},
      {"name":"Psycopg","version":"3.1"}, {"name":"MySQL
      Connector/Python","version":"8.0"},
      {"name":"LightGBM","version":"3.3"}]'
    opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.9"}]'
    argocd.argoproj.io/sync-wave: "2"
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/notebook-image: "true"
lookupPolicy:
  local: true
tag:
  name: "3.3.5"
  referencePolicy:
    type: Local
