---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

commonLabels:
  component: minio

secretGenerator:
- name: minio-root-user
  literals:
  - MINIO_ROOT_USER: admin
  - MINIO_ROOT_PASSWORD: HvA3zAzZd5gLw2E-CRQYPlWaWnK7vy7n

resources:
- namespace.yml
- pvc.yml
- deployment.yml
- service.yml
- route.yml
