---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: envsubst
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: envsubst
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  runPolicy: Serial
  triggers:
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: tools:latest
        namespace: openshift
  source:
    dockerfile: |-
      FROM image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
      RUN dnf -y install gettext \
       && dnf -y clean all
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: envsubst:latest
