---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notebook-demo

commonLabels:
  component: lightgbm-notebook-instance

resources:
- workbench-storage.yml
- notebook.yml
