apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: Demo LightGBM Workbench
    argocd.argoproj.io/sync-wave: "4"
  labels:
    opendatahub.io/dashboard: "true"
  name: demo-lightgbm-workbench
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
