---
apiVersion: v1
kind: Namespace
metadata:
  name: redhat-ods-operator
  annotations:
    openshift.io/display-name: "OpenShift Data Science Operator"
    argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: 'true'
