FROM image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/


COPY Pipfile.lock /opt/app-root/bin/

RUN cd /opt/app-root/bin \
 && micropipenv install \
 && rm -f Pipfile.lock \
 && chmod -R g+w /opt/app-root/lib/python3.9/site-packages \
 && fix-permissions /opt/app-root -P
